version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.2-stretch-node-browsers

    working_directory: /go/src/github.com/wwerner/oaidiff

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS
    - restore_cache:
        keys:
          - v1-pkg-cache
    - run: go get github.com/jstemmer/go-junit-report
    - run: go get -u -v github.com/golang/dep/cmd/dep
    - run: dep ensure -vendor-only -v
    - run:
        name: Test
        command: |
          cd oaidiff_test
          go test -v 2>&1 | go-junit-report > ${TEST_RESULTS}/report.xml
    - store_test_results:
          path: ~/reports
    - store_artifacts:
        path: ~/reports/
        destination: tests/
    - run:
        name: Linux Binaries
        command: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o oaidiff main.go
    - store_artifacts:
        path: ./oaidiff
        destination: dist/linux/oaidiff
    - run:
        name: MacOS Binaries
        command: CGO_ENABLED=0 GOOS=darwin go build -a -installsuffix cgo -o oaidiff main.go
    - store_artifacts:
        path: ./oaidiff
        destination: dist/darwin/oaidiff
    - run:
        name: Windows Binaries (32 bit)
        command: CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -a -installsuffix cgo -o oaidiff main.go
    - store_artifacts:
        path: ./oaidiff
        destination: dist/win32/oaidiff
    - run:
        name: Windows Binaries (64 bit)
        command: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -o oaidiff main.go
    - store_artifacts:
        path: ./oaidiff
        destination: dist/win64/oaidiff

    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

    - store_test_results:
        path: /tmp/test-results

    - setup_remote_docker
    - run: docker build . -t oaidiff:latest
